@hostname = http://localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json
@authTokenClinician = {{authenticate_clinician.response.body.access_token}}
@clinicianId = {{create_clinician.response.body.result.id}}
@patientId = {{create_patient.response.body.result.id}}

###
# @name create_clinician
POST {{host}}/clinicians
Content-Type: {{contentType}}

{
  "name": "John",
  "surname": "Doe",
  "slug": "john-doe",
  "gender": "male",
  "occupation": "doctor",
  "phoneNumber": "123456789",
  "email": "jonhdoe@email.com",
  "password": "12345"
}

### 
# @name authenticate_clinician
POST {{host}}/clinicians/authenticate
Content-Type: {{contentType}}

{
  "email": "jonhdoe@email.com",
  "password": "12345"
}

###
# @name create_patient
POST {{host}}/patients
Content-Type: {{contentType}}

{
  "name": "John",
  "surname": "Doe",
  "slug": "john-doe",
  "gender": "male",
  "birthDate": "2000-01-01T12:00:00.000Z",
  "phoneNumber": "123456789",
  "email": "jonhdoe@email.com",
  "password": "12345"
}

###
# @name create_consultation
POST {{host}}/consultations
Content-Type: {{contentType}}
Authorization: Bearer {{authTokenClinician}}

{
  "room": 1,
  "appointmentDate": "2000-01-01T12:00:00.000Z",
  "clinicianId": "{{clinicianId}}",
  "patientId": "{{patientId}}"
}

###
# @name fetch_recent_consultation
GET {{host}}/consultations?page=3
Content-Type: {{contentType}}
Authorization: Bearer {{authTokenClinician}}

