name: Run E2E tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  
jobs:
  run-e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:alpine3.19
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ghactions
          POSTGRES_PASSWORD: ghactions-password
          POSTGRES_DB: blackwell
      cache:
        image: redis:7.2.7-alpine3.21
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm run test:e2e
        env:
          JWT_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          JWT_PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          DATABASE_URL: "postgresql://ghactions:ghactions-password@localhost:5432/blackwell?schema=public"
